# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "sr.cn.buildpacks.wkhtmltopdf"
version = "0.0.1"
name = "wkhtmltopdf Cloud Native Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
